name: 'Close stale issues'
on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: stale

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        with:
          stale-issue-message: "This has been automatically marked as stale because it has not had recent activity, and will be closed if no further activity occurs. If this was overlooked, forgotten, or should remain open for any other reason, please reply here to call attention to it and remove the stale status. Thank you for your contributions."
          close-issue-message: "This has been automatically closed because it has not had recent activity. Please feel free to update or reopen it."
          stale-pr-message: "This has been automatically marked as stale because it has not had recent activity, and will be closed if no further activity occurs. If this was overlooked, forgotten, or should remain open for any other reason, please reply here to call attention to it and remove the stale status. Thank you for your contributions."
          close-pr-message: "This has been automatically closed because it has not had recent activity. Please feel free to update or reopen it."
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          remove-issue-stale-when-updated: 'true'
          exempt-issue-labels: 'enhancement,bug,minor bug'
          days-before-issue-stale: 90
          days-before-issue-close: 30
          days-before-pr-stale: 900
          days-before-pr-close: 300
          operations-per-run: 200
          ascending: 'false'
          enable-statistics: 'true'
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5.0.1
        with:
          issue-inactive-days: '365'
          issue-lock-reason: 'resolved'
          process-only: 'issues'
